# Include shared CI
include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"

variables:
    # We'll use the single-file case for these runs
    NF_WORKFLOW_OPTS: "--fastq test_data/fastq --sample_sheet test_data/sample_sheet.csv --downsample 50"
    CI_FLAVOUR: "new"
    SKIP_PYTHON_TESTS: "not applicable"

docker-run:
    parallel:
        matrix:
          - MATRIX_NAME: [
            "default", "basecaller-config", "kit14"]
    rules:
        - if: ($CI_COMMIT_BRANCH == null || $CI_COMMIT_BRANCH == "dev-template")
          when: never
        - if: $MATRIX_NAME == "default"
          variables:
              NF_WORKFLOW_OPTS: "--fastq test_data/fastq --sample_sheet test_data/sample_sheet.csv --downsample 50"
        - if: $MATRIX_NAME == "basecaller-config"
          variables:
              NF_WORKFLOW_OPTS: "--fastq test_data/fastq --sample_sheet test_data/sample_sheet.csv --downsample 50 --basecaller_cfg dna_r9.4.1_450bps_hac"
        - if: $MATRIX_NAME == "kit14"
          variables:
              NF_WORKFLOW_OPTS: "--fastq test_data/fastq --sample_sheet test_data/sample_sheet_kit14.csv --downsample 50 --basecaller_cfg dna_r10.4.1_e8.2_400bps_hac"
