name: epi2melabs-nf-template-workflow
channels:
    - epi2melabs
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python==3.8.*
    - aplanat >=0.5.0
    - pysam >=0.17.0
    - fastcat
    - epi2melabs
    - minimap2 ==2.23
    - samtools
    - seqkit ==2.1.0
    - pomoxis <=0.3.9
    - medaka==1.5.0
    - bcftools
